### ISSUE TITLE
Dependecies make it impossible to use

### ISSUE THREAD

**Issue by pleibers** [dynamicslab/NormalFormAE#8]
When following the instructions one runs into the problem that the precompilation always fails. Probably because there is some issue with compatibilities with a newer version of julia (in my case v1.7.3)
A workaround was to delete the manifest.toml, run ] instantiate and then ] build

Not sure how to avoid it from the start

**Comment by mkalia94** [comment]
Hi, that's most likely the case with julia versions as I've been running this code on 1.5.

I will update it for the latest versions but for now your solution works. I will close this now.
