### ISSUE TITLE
Not running. BSON file corrupted. 

### ISSUE THREAD

**Issue by munozdjp** [dynamicslab/NormalFormAE#9]
There is problem with the BSON files that makes it problematic to run.

**Comment by mkalia94** [comment]
Hi, could you provide the output of what you've run and where it fails exactly?

**Comment by munozdjp** [comment]
Yes thanks for your patience on my reply
In particular, the error happened on this line, and when this line's error was run, the following error was shown. The file seems to not be in the right format.
![When running the first line to load the weights the error is displayed](https://user-images.githubusercontent.com/67231886/224566249-bc42ee32-68ae-475a-98e5-1dcadadacb65.png)
![image (2)](https://user-images.githubusercontent.com/67231886/224566253-8354130f-6fa1-4466-b26e-f2e200465ad9.png)

**Comment by munozdjp** [comment]
> Hi, could you provide the output of what you've run and where it fails exactly?

Yes, I just added a new message to the thread with the appropriate output.

**Comment by mkalia94** [comment]
The doi link for the datasets seems fine to me, did you try running the `BSON.@load` command separately to see what was happening? Perhaps you haven't put the BSON files in the correct directory.

**Comment by munozdjp** [comment]
> The doi link for the datasets seems fine to me, did you try running the `BSON.@load` command separately to see what was happening? Perhaps you haven't put the BSON files in the correct directory.

Yes, I have done that, but I still get the same error:
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/67231886/226625725-8e1b9d26-bb7c-4765-a5ea-037b0fb43314.png">

**Comment by mkalia94** [comment]
It seems that there is no backwards compatibility regarding saving ``Flux`` neural networks with ``BSON``, see discussion here, https://discourse.julialang.org/t/bson-error-when-loading-flux-model/78085.

The solution is to run it with Julia 1.5 using ``juliaup`` from https://github.com/JuliaLang/juliaup.

One can then save the ``Flux`` model using the guide here, https://docs.sciml.ai/Flux/stable/guide/saving/, note the warning regarding BSON backwards compatibility issues.
